name: Apply minikube-aws

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: EC2 instance type(minikube needs t2.medium or higher)
        options:
          - "t2.micro"
          - "t2.medium"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023.1.20230809.0
    steps:
      - name: Preprocess for checkout
        run: dnf install -y tar gzip
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Apply
        working-directory: projects/minikube-aws
        run: |
          sh gen-key.sh
          terraform init
          terraform apply -var instance_type=${{ github.event.inputs.instance_type }} -auto-approve